version: '2'

services:

  certs:
    build: cert-generator
    volumes:
      - x509:/x509

  cloud.example.net:
    image: kaazing/enterprise-gateway:5.7.2
    environment:
      GATEWAY_OPTS: "-Dcom.kaazing.kwic.logging=on"
    volumes:
      - ./config/cloud-config.xml:/kaazing-gateway/conf/gateway-config.xml:ro
      - ./config/log4j-config.xml:/kaazing-gateway/conf/log4j-config.xml:ro
    ports:
      - "5551:5551"
    networks:
      kwic-net:

  onprem:
    image: kaazing/enterprise-gateway:5.7.2
    environment:
      GATEWAY_OPTS: "-Dcom.kaazing.kwic.logging=on"
    volumes:
      - ./config/onprem-config.xml:/kaazing-gateway/conf/gateway-config.xml:ro
      - ./config/log4j-config.xml:/kaazing-gateway/conf/log4j-config.xml:ro
      - ./utils/wait-for-files.sh:/wait-for-files.sh:ro
      - x509:/x509:ro
    ports:
      - "6661:6661"
    networks:
      kwic-net:
    command: bash -c "/wait-for-files.sh
                         /x509/stores/keystore-onprem.jceks
                         /x509/stores/keystore-onprem.pw
                         /x509/stores/truststore-onprem.jceks
                         /x509/stores/truststore-onprem.pw
                      && sleep 1
                      && gateway.start"

  example.com:
    image: nginx:1-alpine
    volumes:
      - ./config/nginx.conf:/etc/nginx/nginx.conf:ro
      - ./utils/wait-for-files.sh:/wait-for-files.sh:ro
      - x509:/x509:ro
    networks:
      kwic-net:
    ports:
      - "80:80"
    command: sh -c "/wait-for-files.sh
                         /x509/certs/example.com.crt
                         /x509/certs/example.com.key
                         /x509/ca/client-root-ca.crt
                      && sleep 1
                      && nginx -g 'daemon off;'"

  server-a:
    image: kaazing/enterprise-gateway:5.7.2
    environment:
      GATEWAY_OPTS: "-Dservice-hostname=server-a -Dservice-port=5551"
    volumes:
      - ./config/echo-server-config.xml:/kaazing-gateway/conf/gateway-config.xml:ro
    networks:
      kwic-net:

  server-b:
    image: kaazing/enterprise-gateway:5.7.2
    environment:
      GATEWAY_OPTS: "-Dservice-hostname=server-b -Dservice-port=6661"
    volumes:
      - ./config/echo-server-config.xml:/kaazing-gateway/conf/gateway-config.xml:ro
    networks:
      kwic-net:

volumes:
  x509:

networks:
  kwic-net:
    driver: bridge
    ipam:
      config:
        - subnet: 172.33.0.0/16
          gateway: 172.33.0.1
